# Site settings
title: My Expression
email: shangwenluo6 AT gmail DOT com
description: >
  I do science, I code, and I blog.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://sluo6.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/sluo6
git_edit_address: https://github.com/sluo6/sluo6.github.io

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: readable

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
timezone: US/Chicago
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
